### ISSUE TITLE
Fill matrix summary-box with useful information

### ISSUE THREAD

**Issue by Donnyvdm** [CancerRxGene/gdscmatrixexplorer#26]
As a user I want to see a quick overview of the matrix in the summary view at the top of the page, so I can quickly understand if a matrix is interesting.

Possible use cases:
- Flicking through multiple replicates of the same combination
- Flicking through multiple cell lines for a single combination

Suggestions for things to put in this box:
- A QC summary that highlights the quality of the matrix
- The maximum observed effect of the matrix
- The average Bliss, HSA or Loewe excess for the matrix as a indicator of enhanced combination effect
- Response percentile of this particular cell line compared to all cell lines for the same combination (perhaps of the same tissue type)

**Comment by howard-lightfoot** [comment]
Response percentile would require a consensus on the best metric.
