### ISSUE TITLE
Downloaded results has misaligned column headers

### ISSUE THREAD

**Issue by howard-lightfoot** [CancerRxGene/gdscmatrixexplorer#94]
The results files available for download from the Matrix Explorer webpage seem to have had their column names shifted so that the values in the columns don’t match what you’d expect. For example, for 008 the columns named day1_intensity_mean and day1_intensity_sd are coordinates, e.g. D1 and D3, rather than continuous values. This seems to be the case for 008, 007 and Sandpiper 1.

The mismatch seems to originate with Bliss_window_dose2, which instead of listing a dose, lists a coordinate.

**Comment by Donnyvdm** [comment]
Fixed in v1.0.1
